feat: add passing accuracy analysis
robocin/SoccerAnalyzer pull request #43
Opened 2022-05-16 13:52 UTC by TiagoHRPG

2022-05-25 23:44 UTC, fnalmeidap requested changes
Boa! A análise faz sentido, mas precisamos fazer algumas alterações :)

2022-05-26 00:17 UTC, TiagoHRPG commented on socceranalyzer/common/analysis/passing_accuracy.py
> +        for i in range(0, 10):
Mas do jeito que ta implementado o parametro do goleiro ta setado como falso, ai o players_left.items é um array com 10 elementos só. Eu acho que o array tem os 10 jogadores em campo (tirando o goleiro), colocados nos índices de 0 a 9

2022-05-26 01:08 UTC, fnalmeidap commented on socceranalyzer/common/analysis/passing_accuracy.py
> +        for i in range(0, 10):
Eita, realmente. Não tinha notado :zany_face:

2022-05-26 17:03 UTC, TiagoHRPG commented on socceranalyzer/common/analysis/passing_accuracy.py
> +        self.__left_team_passing_accuracy = 0
Sim, acho que ficaria bem melhor, faria sentido fazer isso com outras análises também

2022-06-06 21:12 UTC, fnalmeidap reviewed
O passing_accuracy.py é a mesma análise de [intercept_counter](https://github.com/robocin/SoccerAnalyzer/blob/develop/socceranalyzer/common/analysis/intercept_counter.py)?

@TiagoHRPG

2022-06-06 22:16 UTC, fnalmeidap approved these changes
No futuro podemos encapsular o algoritmo para utilizar o mesmo código no intercept e no passing accuracy de forma mais modularizada.

2022-06-06 22:16 UTC, merged