Feat: GoalReplay analysis
robocin/SoccerAnalyzer pull request #55
Opened 2022-06-21 14:57 UTC by RonaldSilva42

Análise pedida pela equipe de 2D para verificar a posição da bola e dos players N ciclos antes da ocorrência de um gol.

2022-06-21 15:18 UTC, fnalmeidap requested changes

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +    def __init__(self, dataframe: pandas.DataFrame, category: SSL | SIM2D | VSS, cycles: int) -> None:
Podemos deixar que a escolha de quantos ciclos sejam o replay acontecer no momento que chamamos o método .result(). 

Não precisaríamos do cycles no __ini__ portanto.

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +        self.__find_goals()
O método de construção da análise deve ser o _analyze()

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +    def __find_goals(self) -> None:
Podemos contruir uma outra análise apenas para encontrar os gols.

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +        for i in range(len(self.__dataframe)):
Tentar ao máximo possível não utilizar **for** no dataframe, iterrows é uma alternativa.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +            if ((current_playmode == str(self.__category.GOAL_SCORED_L) or current_playmode == str(self.__category.GOAL_SCORED_R))
Se utilizarmos um dataframe filtrado apenas com os gols, podemos detectar as suas ocorrências mais facilmente.

O [playmode slicer](https://github.com/robocin/SoccerAnalyzer/blob/develop/socceranalyzer/common/utility/slicers.py) pode ser utilizado para filtragem:

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +    def __calculate(self, starting_point: int) -> None:
__calculate deve ser o _analyze (private)

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +            for j in range(11):
No momento, podemos evitar catalogar todos os jogadores e chamar apenas os que são requisitados na chamada do método.

- Um parâmetro de jogadores deve ser criado para isso, provavelmente um dicionário[string, bool];

2022-06-21 15:18 UTC, fnalmeidap commented on socceranalyzer/common/analysis/goal_replay.py
> +    def plot_ball(self, goal_number: int) -> None:
A responsabilidade de plotar o gráfico deve ir para a extensão do jupyter #45

2022-06-22 21:08 UTC, RonaldSilva42 commented on socceranalyzer/common/analysis/goal_replay.py
> +            for j in range(11):
Coloquei um bool para decidir entre calcular ou não as posições dos jogadores, isso porque a partir do momento em que um deles é calculado, a complexidade é a mesma para calcular todos.

2022-06-22 21:09 UTC, RonaldSilva42 commented on socceranalyzer/common/analysis/goal_replay.py
> +            if ((current_playmode == str(self.__category.GOAL_SCORED_L) or current_playmode == str(self.__category.GOAL_SCORED_R))
Depois de fazer isso a perfomance melhorou demais!!

2024-01-21 23:58 UTC, fnalmeidap commented
Closed due to inactivity.

2024-01-21 23:58 UTC, closed without merging